id: P34660EE6
initial_creation_type: input
source_metadata:
  title: Shikpo Lingpa Series
  language: en
  description: 'Texts by the treasure revealer Shikpo Lingpa Gargyi Wangchuk Tsal
    (zhig po gling pa gar gyi dbang phyug rtsal, 1524–1583):'
  volume:
    517134529e2343c9862eabb4e99ac34e:
      title: 'The Sādhana of the Five Self-Arisen Noble Brothers: An Instruction in
        the Union of Generation and Completion'
      parent: Sādhanas
created_at: '2022-03-01T01:37:19.487380'
last_modified_at: '2022-03-01T01:37:19.487386'
